"""
Compute Cohen's kappa and percent agreement between two annotators.

Usage:
    python compute_kappa.py

Prerequisites:
    - annotation_sheet.csv must have 'second_label' column filled in by the second annotator
    - annotation_key.csv must exist (generated by sample_for_annotation.py)

Output:
    Prints agreement stats and a per-label breakdown. Copy results into the README.
"""

import csv
from collections import Counter

SHEET = "annotation_sheet.csv"
KEY = "annotation_key.csv"
LABELS = ["critical_analysis", "visceral_reaction", "hot_take"]


def load_csv(path: str, key_col: str) -> dict[str, dict]:
    rows = {}
    with open(path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            rows[row["id"]] = row
    return rows


def cohen_kappa(y1: list[str], y2: list[str], labels: list[str]) -> float:
    n = len(y1)
    label_idx = {l: i for i, l in enumerate(labels)}
    k = len(labels)

    matrix = [[0] * k for _ in range(k)]
    for a, b in zip(y1, y2):
        if a in label_idx and b in label_idx:
            matrix[label_idx[a]][label_idx[b]] += 1

    po = sum(matrix[i][i] for i in range(k)) / n

    row_totals = [sum(matrix[i]) for i in range(k)]
    col_totals = [sum(matrix[i][j] for i in range(k)) for j in range(k)]
    pe = sum(row_totals[i] * col_totals[i] for i in range(k)) / (n * n)

    return (po - pe) / (1 - pe) if pe != 1 else 1.0


def main():
    key = load_csv(KEY, "id")
    sheet = load_csv(SHEET, "id")

    pairs = []
    skipped = 0
    for id_, s_row in sheet.items():
        second = s_row.get("second_label", "").strip()
        if not second:
            skipped += 1
            continue
        original = key[id_]["original_label"].strip()
        pairs.append((original, second))

    if skipped:
        print(f"Warning: {skipped} rows have no second_label — skipped.")

    if not pairs:
        print("No annotated rows found. Fill in the 'second_label' column in annotation_sheet.csv first.")
        return

    originals, seconds = zip(*pairs)
    n = len(pairs)
    agree = sum(1 for a, b in pairs if a == b)
    pct_agree = agree / n * 100
    kappa = cohen_kappa(list(originals), list(seconds), LABELS)

    print(f"N examples compared: {n}")
    print(f"Percent agreement:   {pct_agree:.1f}%  ({agree}/{n})")
    print(f"Cohen's kappa:       {kappa:.3f}")
    print()

    kappa_interp = (
        "poor (<0.20)" if kappa < 0.20 else
        "fair (0.21–0.40)" if kappa < 0.41 else
        "moderate (0.41–0.60)" if kappa < 0.61 else
        "substantial (0.61–0.80)" if kappa < 0.81 else
        "almost perfect (>0.80)"
    )
    print(f"Interpretation: {kappa_interp} agreement (Landis & Koch scale)")
    print()

    print("Per-label agreement:")
    print(f"  {'Label':<25} {'Orig->Same':>10} {'Orig->Diff':>10}")
    for label in LABELS:
        same = sum(1 for a, b in pairs if a == label and b == label)
        diff = sum(1 for a, b in pairs if a == label and b != label)
        print(f"  {label:<25} {same:>10} {diff:>10}")

    print()
    print("Disagreement breakdown (original -> second_label):")
    disagreements = Counter((a, b) for a, b in pairs if a != b)
    for (a, b), count in sorted(disagreements.items(), key=lambda x: -x[1]):
        print(f"  {a} -> {b}: {count}")


if __name__ == "__main__":
    main()
